# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=250)),
                ('ingredientPicture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ingredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipelName', models.CharField(max_length=250)),
                ('cuisine', models.CharField(max_length=250)),
                ('recipePicture', models.CharField(max_length=1000)),
                ('recipeProcedure', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
