# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_reciped_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciped',
            name='recipePiture',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
