# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_reciped_recipepiture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciped',
            old_name='cuisine',
            new_name='Cuisine',
        ),
        migrations.RenameField(
            model_name='reciped',
            old_name='recipelName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='reciped',
            old_name='recipeProcedure',
            new_name='RecipeProcedure',
        ),
        migrations.RemoveField(
            model_name='reciped',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='reciped',
            name='recipePiture',
        ),
        migrations.AddField(
            model_name='reciped',
            name='RecipePicture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
