# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20171120_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciped',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
