# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_reciped_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciped',
            name='post',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
