# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredientPicture',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientName',
            field=models.CharField(max_length=1000000),
        ),
    ]
